### ISSUE TITLE
Complete tutorial in one notebook

### ISSUE THREAD

**Issue by mdbabumiamssm** [rachelgriffard/optima#1]
Hi, 
Congratulations on the Optima. 
Though you have done an elaborate documentation of the Optima , can you please upload one complete R script package that will contain entire analysis ? 
It will be helpful to understand the comparative pros and cons of Optima in contrast of Mosaic & other existing algorithm used by our collaborators in Mount Sinai & MSKCC. 

Best regards,
Babu

**Comment by rachelgriffard** [comment]
Hello!

Thank you for reaching out. The complete script is contained within the vignette.html file within the repository. In order to view this, you will want to download the file and open it once downloaded.

Please let us know if this is not what you were requesting.

We appreciate it.

Rachel
