### ISSUE TITLE
error found in plotVariantFeature() function

### ISSUE THREAD

**Issue by dtm2117** [rachelgriffard/optima#2]
hello,
I found an error in the plotVariantFeature()
error:   object 'my.obj.filtered' not found

 as you can see below the wrong variable. name is passed to the function.

```
function (optima.obj, vaf.name, reduceDim.obj) 
{
    values = getDNAmtx(my.obj.filtered)[, vaf.name]
    my.df <- data.frame(UMAP1 = reduceDim.obj[[2]][[1]][, 1], 
        UMAP2 = reduceDim.obj[[2]][[1]][, 2], VAF = values)
    ggplot(my.df, aes(UMAP1, UMAP2)) + geom_point(aes(color = VAF), 
        size = 2) + theme_classic() + ggtitle(paste(vaf.name, 
        "VAF"))
}
<bytecode: 0x616c6371b7e0>
<environment: namespace:optima>
```

**Comment by rachelgriffard** [comment]
Hello,

Thank you for bringing this to our attention. We will resolve this issue
and I will let you know once it is fixed.

**Comment by rachelgriffard** [comment]
Hello,

Thank you for bringing this to our attention. It should be resolved within
the package now.

Thank you,
Rachel Griffard
