### ISSUE TITLE
CNV normalisation

### ISSUE THREAD

**Issue by andreyurch** [rachelgriffard/optima#3]
Dear developer, can you please explain a little bit the algorithm and idea behind normalization in normalizeCNV()?

I have not found in publication an explanation of the method.

**Comment by rachelgriffard** [comment]
Hello! Here is a response from the main developer on that part of the package:

"Thank you for your questions. We implemented a similar normalization method as the Mosaic Python package. Here are descriptions for normalization:
https://missionbio.github.io/mosaic/notebooks/cnv.html
“This step is required to correct for systemic artefacts. Cell to cell, and amplicon to amplicon variations are corrected. Each cell is normalized to it’s total reads and each amplicon to its median counts. This is performed using the normalize_reads method, which adds the normalized_counts layer to the CNV object.”"
